db:
  image: alexeiled/docker-oracle-xe-11g
  ports:
    - "1521:1521"
web:
  build: .
  command: python3 manage.py runserver 0.0.0.0:8020
  volumes:
    - .:/code
  ports:
    - "8020:8020"
  links:
    - db
migration:
  build: .
  command: python3 manage.py migrate
  volumes:
    - .:/code
  ports:
    - "8020:8020"
  links:
    - db
