# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 13:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ripcreationrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_dataset_id', models.IntegerField()),
                ('image_take_cat_id', models.IntegerField()),
                ('coverage_poly', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('QU', 'Queued'), ('RU', 'Running'), ('CO', 'Completed'), ('FA', 'Failed'), ('RE', 'To be retried')], default='QU', max_length=2)),
                ('acquisition_datetime', models.DateTimeField()),
                ('cataloging_datetime', models.DateTimeField()),
                ('queued_datetime', models.DateTimeField()),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('image_take_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ripcreationrequest',
            unique_together=set([('archive_dataset_id', 'image_take_metadata')]),
        ),
    ]
