# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20160622_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldborder',
            old_name='geom',
            new_name='mpoly',
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='fips',
            field=models.CharField(max_length=2, verbose_name='FIPS Code'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso2',
            field=models.CharField(max_length=2, verbose_name='2 Digit ISO'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso3',
            field=models.CharField(max_length=3, verbose_name='3 Digit ISO'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='pop2005',
            field=models.IntegerField(verbose_name='Population 2005'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='region',
            field=models.IntegerField(verbose_name='Region Code'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='subregion',
            field=models.IntegerField(verbose_name='Sub-Region Code'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='un',
            field=models.IntegerField(verbose_name='United Nations Code'),
        ),
    ]
